"""Stable reason-code constants for the technical prediction layer.

These are advisory diagnostic codes attached to signals, predictions, and
dashboard cards. They are NOT authorization outcomes — the authoritative
accept/reject reasons still come from ProfitabilityGate / RiskManager.
Keeping them as named constants avoids typos and lets the GUI/tests reference
one source of truth.
"""

from __future__ import annotations

# Availability / quality
TECHNICAL_SIGNAL_UNAVAILABLE = "TECHNICAL_SIGNAL_UNAVAILABLE"
TECHNICAL_CONFIDENCE_TOO_LOW = "TECHNICAL_CONFIDENCE_TOO_LOW"
TECHNICAL_EDGE_NON_POSITIVE = "TECHNICAL_EDGE_NON_POSITIVE"

# Momentum
MOMENTUM_CONFIRMED = "MOMENTUM_CONFIRMED"
MOMENTUM_WEAKENED = "MOMENTUM_WEAKENED"

# Breakout
BREAKOUT_CONFIRMED = "BREAKOUT_CONFIRMED"
FALSE_BREAKOUT_RISK_HIGH = "FALSE_BREAKOUT_RISK_HIGH"

# Mean reversion
MEAN_REVERSION_CANDIDATE = "MEAN_REVERSION_CANDIDATE"
MEAN_REVERSION_BLOCKED_BY_DOWNTREND = "MEAN_REVERSION_BLOCKED_BY_DOWNTREND"

# VWAP / volume
VWAP_CONFIRMATION_OK = "VWAP_CONFIRMATION_OK"
VWAP_BREAKDOWN = "VWAP_BREAKDOWN"
VOLUME_CONFIRMATION_MISSING = "VOLUME_CONFIRMATION_MISSING"

# Liquidity / volatility / spread blocks
LOW_LIQUIDITY_TECHNICAL_BLOCK = "LOW_LIQUIDITY_TECHNICAL_BLOCK"
HIGH_VOLATILITY_TECHNICAL_BLOCK = "HIGH_VOLATILITY_TECHNICAL_BLOCK"
SPREAD_CONSUMES_TECHNICAL_ALPHA = "SPREAD_CONSUMES_TECHNICAL_ALPHA"

# Risk / exit
TECHNICAL_DOWNSIDE_RISK_HIGH = "TECHNICAL_DOWNSIDE_RISK_HIGH"
TECHNICAL_EXIT_DETERIORATION = "TECHNICAL_EXIT_DETERIORATION"

ALL_REASON_CODES = (
    TECHNICAL_SIGNAL_UNAVAILABLE,
    TECHNICAL_CONFIDENCE_TOO_LOW,
    TECHNICAL_EDGE_NON_POSITIVE,
    MOMENTUM_CONFIRMED,
    MOMENTUM_WEAKENED,
    BREAKOUT_CONFIRMED,
    FALSE_BREAKOUT_RISK_HIGH,
    MEAN_REVERSION_CANDIDATE,
    MEAN_REVERSION_BLOCKED_BY_DOWNTREND,
    VWAP_CONFIRMATION_OK,
    VWAP_BREAKDOWN,
    VOLUME_CONFIRMATION_MISSING,
    LOW_LIQUIDITY_TECHNICAL_BLOCK,
    HIGH_VOLATILITY_TECHNICAL_BLOCK,
    SPREAD_CONSUMES_TECHNICAL_ALPHA,
    TECHNICAL_DOWNSIDE_RISK_HIGH,
    TECHNICAL_EXIT_DETERIORATION,
)
